apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
  namespace: booking
data:
  PORT: "5000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "bookingdb"
  DB_USER: "booking"
  USER_SERVICE_URL: "http://user-service:5003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5002"
